### ISSUE TITLE
Can't get google sign in button to load

### ISSUE THREAD

**Issue by sheehanmunim** [mettiuss/swift-googlesignin#1]
Hi there. I've copied everything you've shown exactly (Created my own ExampleApp just to be safe), but everytime I hit the signin with google button, it never loads. I've added all the google plist files and everything correctly.
![image](https://github.com/mettiuss/swift-googlesignin/assets/80079528/f226b495-b8cd-4f5d-8d6e-14116875b880)

**Comment by mettiuss** [comment]
Hello, have you been able to find the issue on your own?

Let me know if you need any help!

**Comment by sheehanmunim** [comment]
Yes, thank you.
