### ISSUE TITLE
Update for Xcode 15.4

### ISSUE THREAD

**Issue by nigels0** [mettiuss/swift-googlesignin#3]
Just an update for the latest (for now) build of Xcode, you need to add 
`import UIKit`  
`import FirebaseAuth` into Authentication.swift

to get this to work

**Comment by mettiuss** [comment]
I just tested this using Xcode 16 beta 4 (I cannot run it on 15.4 because I'm on macOS Someda). But it seems to work fine, did you maybe change anything else in the file? What error does it throw when these imports are not specified?

**Comment by nigels0** [comment]
I'm using Xcode 15.4, Sonoma 14.5 Firebase package is 11.0 on a M1 Mac Mini and without these, I'm getting the following errors:
`  /Users/x/xcode/swift-googlesignin/Example/Authentication.swift:42:26 Cannot find 'GoogleAuthProvider' in scope

/Users/x/xcode/swift-googlesignin/Example/Authentication.swift:45:19 Cannot find 'Auth' in scope`

Having said that - it now seems OK without needing UIKit imported!

**Comment by mettiuss** [comment]
Okay, turns out `import Firebase` is not the right way to import Firebase.
I made a commit that should fix this issue, could you check if it is now working? I still could not reproduce the same error.

**Comment by nigels0** [comment]
Yes, that works - but you don't need to include FirebaseCore for it to work
